import {
  pgTable,
  uuid,
  varchar,
  text,
  integer,
  jsonb,
  timestamp,
  date,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { stores } from "./stores";
import { users } from "./users";
import { products } from "./products";

/**
 * AI Tool Enums & Statuses
 */
export const AI_TOOLS = [
  "AI_PRODUCT_TITLE",
  "AI_PRODUCT_DESCRIPTION",
  "AI_SEO_DESCRIPTION",
  "AI_PRODUCT_FEATURES",
  "AI_PRODUCT_SPECIFICATIONS",
  "AI_PRODUCT_TAGS",
  "AI_CATEGORY_SUGGESTION",
] as const;

export type AiToolType = (typeof AI_TOOLS)[number];

export const AI_REQUEST_STATUSES = [
  "GENERATING",
  "SUCCEEDED",
  "FAILED",
  "REJECTED",
  "APPLIED",
  "DISMISSED",
] as const;

export type AiRequestStatusType = (typeof AI_REQUEST_STATUSES)[number];

/**
 * 1. AI Requests
 * Audit log of every invocation of an AI intelligence tool.
 * Strictly scoped by store and authenticated user.
 */
export const aiRequests = pgTable(
  "ai_requests",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    storeId: uuid("store_id")
      .notNull()
      .references(() => stores.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    productId: uuid("product_id").references(() => products.id, {
      onDelete: "set null",
    }),
    tool: varchar("tool", { length: 50 }).notNull(), // One of AI_TOOLS
    provider: varchar("provider", { length: 50 }).notNull(), // e.g. "mock", "gemini", "openai"
    model: varchar("model", { length: 100 }).notNull(),
    status: varchar("status", { length: 50 }).notNull().default("GENERATING"),
    inputTokensEstimate: integer("input_tokens_estimate").notNull().default(0),
    outputTokensEstimate: integer("output_tokens_estimate").notNull().default(0),
    errorMessage: text("error_message"),
    metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("idx_ai_requests_store_id").on(table.storeId),
    index("idx_ai_requests_product_id").on(table.productId),
    index("idx_ai_requests_tool").on(table.storeId, table.tool),
    index("idx_ai_requests_created_at").on(table.storeId, table.createdAt),
  ]
);

/**
 * 2. AI Generation History
 * Tracks suggestions generated by AI, previous values, and merchant apply/reject decisions.
 */
export const aiGenerationHistory = pgTable(
  "ai_generation_history",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    storeId: uuid("store_id")
      .notNull()
      .references(() => stores.id, { onDelete: "cascade" }),
    requestId: uuid("request_id")
      .notNull()
      .references(() => aiRequests.id, { onDelete: "cascade" }),
    productId: uuid("product_id")
      .notNull()
      .references(() => products.id, { onDelete: "cascade" }),
    tool: varchar("tool", { length: 50 }).notNull(),
    originalValue: jsonb("original_value").$type<unknown>(),
    generatedSuggestion: jsonb("generated_suggestion").$type<unknown>().notNull(),
    status: varchar("status", { length: 50 }).notNull().default("SUGGESTED"), // SUGGESTED, APPLIED, REJECTED, DISMISSED
    appliedAt: timestamp("applied_at", { withTimezone: true }),
    appliedBy: uuid("applied_by").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("idx_ai_history_store_id").on(table.storeId),
    index("idx_ai_history_product_id").on(table.productId),
    index("idx_ai_history_request_id").on(table.requestId),
  ]
);

/**
 * 3. AI Usage Ledger
 * Aggregated daily usage per store for quota limits and Phase 15 billing foundation.
 */
export const aiUsageLedger = pgTable(
  "ai_usage_ledger",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    storeId: uuid("store_id")
      .notNull()
      .references(() => stores.id, { onDelete: "cascade" }),
    date: date("date").notNull(), // YYYY-MM-DD
    requestCount: integer("request_count").notNull().default(0),
    successCount: integer("success_count").notNull().default(0),
    failureCount: integer("failure_count").notNull().default(0),
    tokensUsed: integer("tokens_used").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("idx_ai_usage_store_date").on(table.storeId, table.date),
    index("idx_ai_usage_store_id").on(table.storeId),
  ]
);

export type AiRequest = typeof aiRequests.$inferSelect;
export type NewAiRequest = typeof aiRequests.$inferInsert;
export type AiGenerationHistory = typeof aiGenerationHistory.$inferSelect;
export type NewAiGenerationHistory = typeof aiGenerationHistory.$inferInsert;
export type AiUsageLedger = typeof aiUsageLedger.$inferSelect;
export type NewAiUsageLedger = typeof aiUsageLedger.$inferInsert;
